vim.keymap.set('i', 'jj', '<Esc>')
vim.keymap.set('n', 'ew', '<C-w><C-w>')
vim.keymap.set('n', 'eh', '<C-w>h')
vim.keymap.set('n', 'el', '<C-w>l')
vim.keymap.set('n', '<leader>;', 'A;<Esc>')
vim.keymap.set('n', '<leader>e', ':Lexplore<CR>')
vim.keymap.set('n', '<leader>w', ':w<CR>')
vim.keymap.set('n', '<leader>wq', ':wq<CR>')
vim.keymap.set('n', '<leader>q', ':q<CR>')
vim.keymap.set('n', '<leader>qq', ':q!<CR>')
vim.keymap.set('n', '<leader>re', ':so<Space>%<CR>')
vim.keymap.set('n', '<leader>st', ':e<Space>**/*.ts')
vim.keymap.set('n', '<leader>sj', ':e<Space>**/*.js')
vim.keymap.set('n', '<leader>sx', ':e<Space>**/*.tsx')
vim.keymap.set('n', '<leader>t', ':terminal<CR>')
vim.keymap.set('n', '<leader>y', '"+yy:echo "copied to calipboard"<CR>')
vim.keymap.set('n', '<leader>p', '"+p:echo "pasted from calipboard"<CR>')
vim.keymap.set('v', '<leader>y', '"+yy:echo "copied to calipboard"<CR>')
vim.keymap.set('v', '<leader>p', '"+p:echo "pasted from calipboard"<CR>')
vim.keymap.set('t', 'jj', '<C-\\><C-n>')
vim.keymap.set('t', '<leader>gf', '<C-w>F')
vim.keymap.set('n', '<c-j>', ':cnext<CR>')
vim.keymap.set('n', '<c-k>', ':cprev<CR>')
vim.keymap.set('n', '<leader>j', ':lnext<CR>')
vim.keymap.set('n', '<leader>k', ':lprev<CR>')
